Fix: wwwroot is not configurable
bitnami/bitnami-docker-moodle pull request #195
Opened 2022-01-20 19:19 UTC by fatiiates

Signed-off-by: Fatih ATES <fatiiates@gmail.com>

**Description of the change**

At the company where I did my internship, I was asked to run moodle and I did, but I couldn't scale it. I ran into a problem because I couldn't configure the wwwroot when I configured with Nginx. And I solved this problem by changing source code instead of give config.php as volume. So I created a simpler .yml file. I noticed different people are having the same issue, so I'm throwing a PR.

**Benefits**

The wwwroot configuration will become controllable with the MOODLE_HOST env variable.

**Possible drawbacks**

I think there is no limitation with my change.

**Applicable issues**

#58 
#146 

**Additional Information**

```
# docker-compose.yml
version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  moodle:
    image: moodletest-new
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MOODLE_SITE_NAME=BBB MOODLE
      - MOODLE_HOST=192.168.1.9
      - BITNAMI_DEBUG=1
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local

```

And the result;
![2022-01-20_21-58](https://user-images.githubusercontent.com/51250249/150407258-57b506a5-7560-4d00-a3d0-3046a93aee61.png)

2022-01-21 07:30 UTC, juan131 requested changes
Hi @fatiiates 

Thanks so much for your contribution! We really appreciate it!

Could you please check my comments when you have a chance? Also, could you please update the README.md including the information about the new. enviable you added? Thanks in advance.

2022-01-21 07:30 UTC, juan131 commented on 3/debian-10/rootfs/opt/bitnami/scripts/moodle-env.sh
> +MOODLE_HOST="${MOODLE_HOST:-}"
I don't thin this line adds any value. I mean, the one below should be enough.

2022-01-21 07:30 UTC, juan131 commented on 3/debian-10/rootfs/opt/bitnami/scripts/libmoodle.sh
> +    fi
Why don't you set a default value in the `moodle-env.sh` instead? 
```diff
-export MOODLE_HOST="${MOODLE_HOST:-}"
+export MOODLE_HOST="${MOODLE_HOST:-"\$_SERVER['HTTP_HOST']"}"
```

2022-01-21 18:47 UTC, fatiiates commented on 3/debian-10/rootfs/opt/bitnami/scripts/libmoodle.sh
> +    fi
You're right. The above line is not needed. However, I still think two lines are needed.

    MOODLE_HOST="${MOODLE_HOST:+"'${MOODLE_HOST}'"}"
    export MOODLE_HOST="${MOODLE_HOST:-"\$_SERVER['HTTP_HOST']"}"

When it is default, there is no need for quotes as it is already a PHP code. However, when there is a value, we should write that value in quotation marks and write it to the config.php file. 

I get a bad substitution error when I try to do it in one line.

    export MOODLE_HOST="${${MOODLE_HOST:+'${MOODLE_HOST}'}:-"\$_SERVER['HTTP_HOST']"}"

This line gives the following error.

    line 13: export MOODLE_HOST="${${MOODLE_HOSTT+'${MOODLE_HOST}'}:-"\$_SERVER['HTTP_HOST']"}": bad substitution

Do you think it can be solved in one line?

2022-01-24 08:03 UTC, juan131 commented on 3/debian-10/rootfs/opt/bitnami/scripts/libmoodle.sh
> +    fi
All right.. I didn't realize you were forcing a quotation to the string passed via `MOODLE_HOST`. Feel free to keep it using two lines then.

2022-01-24 21:24 UTC, fatiiates commented
I tried to finish it in two lines, but we were facing another problem. moodle-env.sh script is run twice at container runtime. Therefore, as seen in the screenshot below, there was `a pair of single quotes` problem.

![bitnami-repeat-real](https://user-images.githubusercontent.com/51250249/150866199-44dfe6ea-012c-4966-885e-ce5832b4a6cd.png)

Therefore, it was necessary to remember the initial host value. I realized the recall with the following two lines.

    INITIAL_MOODLE_HOST="${INITIAL_MOODLE_HOST:-"${MOODLE_HOST:+"'${MOODLE_HOST}'"}"}" # only used during the first initialization  
    export INITIAL_MOODLE_HOST="${INITIAL_MOODLE_HOST:-"\$_SERVER['HTTP_HOST']"}" # only used during the first initialization  

Finally, I assigned the wanted host value to MOODLE_HOST env variable.

    export MOODLE_HOST="${INITIAL_MOODLE_HOST:-}" # only used during the first initialization

Do you think anything better can be done?

2022-01-25 08:00 UTC, juan131 commented
> `moodle-env.sh` script is run twice at container runtime. Therefore, as seen in the screenshot below, there was a pair of single quotes problem.

Good catch!! That's definitely gonna be problematic.

> Do you think anything better can be done?

I think the best option we have here is to move this env. var "sanitization" back to `moodle_configure_wwwroot` function.

2022-01-25 10:01 UTC, fatiiates commented
I think so too, I applied the changes as you requested.

2022-01-25 17:11 UTC, juan131 approved these changes
LGTM! I'll send the changes for internal review and let you know when they're accepted and a new image is released including them.

2022-01-26 07:40 UTC, merged

2022-01-26 09:57 UTC, juan131 commented
Hi @fatiiates 

A new image version (`3.11.5-debian-10-r10`) was just released including your changes, see:

- https://github.com/bitnami/bitnami-docker-moodle/commit/8f69a12ef5d499f39dbddcd541afbaaf637124cb

2022-01-26 11:11 UTC, fatiiates commented
That's good news! But I realized I forgot something. I accidentally forgot to update the README.md file while editing my commits. 

Do you want me to open a new PR for this?

2022-01-26 14:59 UTC, juan131 commented
Hi @fatiiates 

The commit below already did that, please take a look.

2022-02-04 18:49 UTC, fspasovski commented
Hi, this solution worked great, but I was getting a redirect loop since my container is behind a nginx. Could we pass additional properties to include `$CFG->reverseproxy = true;` in  `/bitnami/module/config.php`, and not update it manually? 

Tnx.

2022-02-04 19:17 UTC, fatiiates commented
Hey  @fspasovski, I guess we're both working for the same goals. I created this PR because I was having problems with nginx too. After configure the wwwroot variable, I came across reverseproxy, but I couldn't create a new PR because I didn't have time. So, I did not perform an update to update reverseproxy in the code.

I have created a new [issue](https://github.com/bitnami/bitnami-docker-moodle/issues/198) now. I will try to be interested.