Support for Postgresql
bitnami/bitnami-docker-moodle pull request #197
Opened 2022-02-03 09:51 UTC by sbaerlocher

**Description of the change**

In this PR the Postgresql support was added as described in #157.

**Benefits**

The Moodle container gets support for the Postgresql database.

2022-02-04 12:31 UTC, marcosbc requested changes
Thanks for this awesome PR! Please have a look at my comment and let us know if you have any questions.

2022-02-04 12:31 UTC, marcosbc commented on 3/debian-10/rootfs/opt/bitnami/scripts/libmoodle.sh
> +        [[ "$db_type" = "mariadb" || "$db_type" = "mysqli" || "$db_type" = "pgsql" ]] && moodle_wait_for_db_connection "$db_host" "$db_port" "$db_name" "$db_user" "$db_pass"
I would recommend to create a new function for checking PostgreSQL connections, i.e.:

```suggestion
        [[ "$db_type" = "mariadb" || "$db_type" = "mysqli" ]] && moodle_wait_for_mysql_connection "$db_host" "$db_port" "$db_name" "$db_user" "$db_pass"
        [[ "$db_type" = "pgsql" ]] && moodle_wait_for_postgresql_connection "$db_host" "$db_port" "$db_name" "$db_user" "$db_pass"
```

2022-02-04 12:31 UTC, marcosbc commented on 3/debian-10/rootfs/opt/bitnami/scripts/libmoodle.sh
> +fi
Small request to make it compatible with more environments (not strictly containers):
```suggestion
if [[ -f /opt/bitnami/scripts/libpostgresqlclient.sh ]]; then
    . /opt/bitnami/scripts/libpostgresqlclient.sh
elif [[ -f /opt/bitnami/scripts/libpostgresql.sh ]]; then
    . /opt/bitnami/scripts/libpostgresql.sh
fi
```

2022-02-04 12:31 UTC, marcosbc commented on 3/debian-10/rootfs/opt/bitnami/scripts/libmoodle.sh
> +                    postgresql_remote_execute "${mysql_execute_args[@]}" <<EOF
Since the queries are the same, we could simplify this a lot:

```bash
local db_remote_execute="mysql_remote_execute"
[[ "$db_type" = "pgsql" ]] && db_remote_execute="postgresql_remote_execute"
...
echo "..." | "$db_remote_execute" "${db_execute_args[@]}"
...
```

If they are not the same, it would be worth finding an equivalent that works in the same way for both DB types.

2022-02-04 12:31 UTC, marcosbc commented on 3/debian-10/rootfs/opt/bitnami/scripts/libmoodle.sh
>              local -a mysql_execute_args=("$db_host" "$db_port" "$db_name" "$db_user" "$db_pass")
```suggestion
            local -a db_execute_args=("$db_host" "$db_port" "$db_name" "$db_user" "$db_pass")
```

2022-02-04 12:31 UTC, marcosbc commented on 3/debian-10/rootfs/opt/bitnami/scripts/libmoodle.sh
> +       [[ "$db_type" = "mariadb" || "$db_type" = "mysqli" || "$db_type" = "pgsql" ]] && moodle_wait_for_db_connection "$db_host" "$db_port" "$db_name" "$db_user" "$db_pass"
I would recommend to create a new function for checking PostgreSQL connections, i.e.:

```suggestion
        [[ "$db_type" = "mariadb" || "$db_type" = "mysqli" ]] && moodle_wait_for_mysql_connection "$db_host" "$db_port" "$db_name" "$db_user" "$db_pass"
        [[ "$db_type" = "pgsql" ]] && moodle_wait_for_postgresql_connection "$db_host" "$db_port" "$db_name" "$db_user" "$db_pass"
```

2022-02-04 12:31 UTC, marcosbc commented on 3/debian-10/rootfs/opt/bitnami/scripts/libmoodle.sh
> +moodle_wait_for_db_connection() {
As mentioned above, we should consider splitting this function.

2022-02-04 12:31 UTC, marcosbc commented on README.md
> +##### Create a database for Moodle using postgresql-client
Could we include this section instead below "Create a database for Moodle using mysql-client"?

2022-02-08 19:28 UTC, marcosbc requested changes
Looking pretty great now! I have a small request that I'd prefer to have solved before merging, could you check it?

2022-02-08 19:28 UTC, marcosbc commented on 3/debian-10/rootfs/opt/bitnami/scripts/moodle/entrypoint.sh
> +    fi
My understanding is that the `setup.sh` for both `mysql-client` and `postgresql-client` have a check for avoiding execution if the `MYSQL_CLIENT_*` or `POSTGRESQL_CLIENT_*` environment variables are not set. Could you check this? Leaving it like this should work fine:

```suggestion
    /opt/bitnami/scripts/mysql-client/setup.sh
    /opt/bitnami/scripts/postgresql-client/setup.sh
```

2022-02-08 22:23 UTC, sbaerlocher commented on 3/debian-10/rootfs/opt/bitnami/scripts/moodle/entrypoint.sh
> +    fi
I have thrown it over, it works accordingly without the check.

2022-02-09 11:53 UTC, marcosbc approved these changes
Thanks! LGTM!

2022-02-09 15:46 UTC, merged