Fix: $CFG->reverseproxy is not configurable
bitnami/bitnami-docker-moodle pull request #199
Opened 2022-02-06 19:22 UTC by fatiiates

Signed-off-by: Fatih ATES <fatiiates@gmail.com>

**Description of the change**

After configure the wwwroot variable with this [PR](https://github.com/bitnami/bitnami-docker-moodle/pull/195), I came across reverseproxy. I had to manually change the $CFG->reverseproxy variable to get it behind the load balancer. But this is useless and requires you to change data in volume. I added two new environment variables named MOODLE_REVERSEPROXY and MOODLE_SSLPROXY and configured config.php with them.

**Benefits**

- REVERSEPROXY and SSLPROXY properties no longer need to be changed manually in config.php.
- Additionally, I fixed a bug that prevented the use of the MOODLE_HOST variable and updated the README by adding an example usage in the documentation.

**Possible drawbacks**

If the SSLPROXY feature is turned on, absolutely all server requests must be used with HTTPS.

**Applicable issues**

#198

2022-02-06 19:24 UTC, fatiiates commented
Hey @fspasovski, this is the PR I created about the REVERSEPROXY feature. You can follow it here.

2022-02-06 19:28 UTC, fspasovski commented
@fatiiates Tnx for the update, looking forward to this.

2022-02-08 07:35 UTC, juan131 requested changes
Thanks so much for this awesome PR @fatiiates!! Please check my comments when you have a chance.

2022-02-08 07:35 UTC, juan131 commented on 3/debian-10/rootfs/opt/bitnami/scripts/libmoodle.sh
> +    fi
In the **README.md**, you mentioned that the default value is "no". On the other hand, the env. var validation should be done in `moodle_validate` function: 
```suggestion
    # Checking the reverseproxy setting values
    is_boolean_yes "$MOODLE_REVERSEPROXY" && echo "\$CFG->reverseproxy = true;" >> "$MOODLE_CONF_FILE"
    # Checking the sslproxy setting values
    is_boolean_yes "$MOODLE_SSLPROXY" && echo "\$CFG->sslproxy = true;" >> "$MOODLE_CONF_FILE"
    # Avoid exit code of previous commands to affect the result of this function
    true
```

And add to `moodle_validate`:
```bash
    check_yes_no_value() {
        if ! is_yes_no_value "${!1}" && ! is_true_false_value "${!1}"; then
            print_validation_error "The allowed values for ${1} are: yes no"
        fi
    }
    ...
    check_yes_no_value "MOODLE_REVERSEPROXY"
    check_yes_no_value "MOODLE_SSLPROXY"
```

2022-02-08 07:35 UTC, juan131 commented on 3/debian-10/rootfs/opt/bitnami/scripts/moodle-env.sh
> +export MOODLE_SSLPROXY="${MOODLE_SSLPROXY:-}" # only used during the first initialization
Default value should be "no":
```suggestion
export MOODLE_REVERSEPROXY="${MOODLE_REVERSEPROXY:-no}" # only used during the first initialization
export MOODLE_SSLPROXY="${MOODLE_SSLPROXY:-no}" # only used during the first initialization
```

2022-02-10 07:33 UTC, juan131 approved these changes
Awesome thanks! I'll send your changes for internal review and keep you updated about the progress

2022-02-10 08:40 UTC, fatiiates commented
Thank you too. We really appreciate your help. I look forward to the review of the changes!!

2022-02-10 10:04 UTC, merged

2022-02-10 10:43 UTC, juan131 commented
@fatiiates the new `3.11.5-debian-10-r27` release includes your changes, see:

- https://github.com/bitnami/bitnami-docker-moodle/commit/0020dd1b01a59a8163f8232cd94ff57509613744

2022-02-11 12:08 UTC, fspasovski commented
Hi,
I recently pulled `3.11.5-debian-10-r27` image and I noticed that the `$CFG->reverseproxy = true;` is configured properly, although I still get the redirect loop issue. 
I am not familiar with php, but I inspected the `config.php` file that is generated and it has the following structure:

```php
<?php  // Moodle configuration file

unset($CFG);
global $CFG;
$CFG = new stdClass();

$CFG->dbtype    = 'mariadb';
$CFG->dblibrary = 'native';
$CFG->dbhost    = 'mariadb';
$CFG->dbname    = 'mydbname';
$CFG->dbuser    = 'mydbuser';
$CFG->dbpass    = 'mydbpass';
$CFG->prefix    = 'mdl_';
$CFG->dboptions = array (
  'dbpersist' => 0,
  'dbport' => 3306,
  'dbsocket' => '',
  'dbcollation' => 'utf8mb4_unicode_ci',
);

if (empty($_SERVER['HTTP_HOST'])) {
  $_SERVER['HTTP_HOST'] = '127.0.0.1:8080';
}
if (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on') {
  $CFG->wwwroot   = 'https://' . 'mydomain';
} else {
  $CFG->wwwroot   = 'http://' . 'mydomain';
}
$CFG->dataroot  = '/bitnami/moodledata';
$CFG->admin     = 'admin';

$CFG->directorypermissions = 02775;

require_once(__DIR__ . '/lib/setup.php');

// There is no php closing tag in this file,
// it is intentional because it prevents trailing whitespace problems!
$CFG->reverseproxy = true;
```

In order to get this to work, I had to manually move the `$CFG->reverseproxy = true;` above the `require_once(__DIR__ . '/lib/setup.php');` line.
If I am missing something here, any help would be appreciated. 

Thanks.